module.exports = {
  "ALIVE_IMG": "𝙷𝙴𝙻𝙻𝙾𝚆👋 𝙸'𝙼 𝙰𝙻𝙸𝚅𝙴 𝙽𝙾𝚆! 𝙸'𝙼 𝙳𝙴𝙽𝙴𝚃𝙷 𝚁𝙰𝚂𝙸𝙽𝙳𝚄 𝙽𝙸𝙼𝚂𝙰𝚁𝙰, 𝚃𝚈𝙿𝙴 `.menu` GET COMMANDS.😇",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "public",
  "BOT_NUMBER": "94774563898",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": true,
  "WELCOME": false,
  "ANTI_BAD": false,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "𝒟𝑒𝓃𝑒𝓉𝒽 𝑅𝒶𝓈𝒾𝓃𝒹𝓊 𝒩𝒾𝓂𝓈𝒶𝓇𝒶",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": true,
  "EMOJI": "🏷"
};
